### ISSUE TITLE
Make the 3 sec cooldown configurable

### ISSUE THREAD

**Issue by Malachiel87** [addstar/geSuitTeleport#2]
Is possible to make to add the option in config to disable 3 second teleport? Is prettty anoying for somesone

**Comment by xion87** [comment]
ehm @addstar i tried now to add the permission gesuit.teleports.bypass.delay, not working...

**Comment by addstar** [comment]
I can 100% confirm that the bypass permission is "gesuit.teleports.bypass.delay". Sorry, but you must be setting the permission wrong or it's not being applied correctly by your permission manager.

See the code:
* [/tpaccept delay bypass code](https://github.com/addstar/geSuitTeleport/blob/master/src/main/java/net/cubespace/geSuitTeleports/managers/TeleportsManager.java#L105)
* [/back delay bypass code](https://github.com/addstar/geSuitTeleport/blob/master/src/main/java/net/cubespace/geSuitTeleports/managers/TeleportsManager.java#L204)
* [/tp delay bypass code](https://github.com/addstar/geSuitTeleport/blob/master/src/main/java/net/cubespace/geSuitTeleports/managers/TeleportsManager.java#L326)

**Comment by ghacproductions** [comment]
I just tested it too, it doesn't work with that permission, although it's in the code... A player having operator permissions can bypass the delay, a player with permission gesuit.teleports.bypass.delay not.

**Comment by addstar** [comment]
This means you permission manager isnt working properly, or you're not setting the correct permission. Sorry but I'm positive it works. Can you describe exactly what you are doing and which permission manager you use?
